/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KangxuanRouteImport } from './routes/kangxuan'
import { Route as RianRouteImport } from './routes/rian'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KangxuanRoute = KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => rootRouteImport,
} as any)
const RianRoute = RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kangxuan' | '/rian'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kangxuan' | '/rian'
  id: '__root__' | '/' | '/kangxuan' | '/rian'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KangxuanRoute: typeof KangxuanRoute
  RianRoute: typeof RianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kangxuan': {
      id: '/kangxuan'
      path: '/kangxuan'
      fullPath: '/kangxuan'
      preLoaderRoute: typeof KangxuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rian': {
      id: '/rian'
      path: '/rian'
      fullPath: '/rian'
      preLoaderRoute: typeof RianRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KangxuanRoute: KangxuanRoute,
  RianRoute: RianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
