/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KangxuanRouteImport } from './routes/kangxuan'
import { Route as RianRouteImport } from './routes/rian'
import { Route as V10CtlPanelRouteImport } from './routes/v10CtlPanel'
import { Route as V8RouteImport } from './routes/v8'
import { Route as V8testRouteImport } from './routes/v8test'
import { Route as V9RouteImport } from './routes/v9'
import { Route as V9testRouteImport } from './routes/v9test'
import { Route as V8KangxuanRouteImport } from './routes/v8.kangxuan'
import { Route as V8RianRouteImport } from './routes/v8.rian'
import { Route as V8PreviewRouteImport } from './routes/v8_.preview'
import { Route as V8testKangxuanRouteImport } from './routes/v8test.kangxuan'
import { Route as V8testRianRouteImport } from './routes/v8test.rian'
import { Route as V9KangxuanRouteImport } from './routes/v9.kangxuan'
import { Route as V9RianRouteImport } from './routes/v9.rian'
import { Route as V9testKangxuanRouteImport } from './routes/v9test.kangxuan'
import { Route as V9testRianRouteImport } from './routes/v9test.rian'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KangxuanRoute = KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => rootRouteImport,
} as any)
const RianRoute = RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => rootRouteImport,
} as any)
const V10CtlPanelRoute = V10CtlPanelRouteImport.update({
  id: '/v10CtlPanel',
  path: '/v10CtlPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const V8Route = V8RouteImport.update({
  id: '/v8',
  path: '/v8',
  getParentRoute: () => rootRouteImport,
} as any)
const V8testRoute = V8testRouteImport.update({
  id: '/v8test',
  path: '/v8test',
  getParentRoute: () => rootRouteImport,
} as any)
const V9Route = V9RouteImport.update({
  id: '/v9',
  path: '/v9',
  getParentRoute: () => rootRouteImport,
} as any)
const V9testRoute = V9testRouteImport.update({
  id: '/v9test',
  path: '/v9test',
  getParentRoute: () => rootRouteImport,
} as any)
const V8KangxuanRoute = V8KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V8Route,
} as any)
const V8RianRoute = V8RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V8Route,
} as any)
const V8PreviewRoute = V8PreviewRouteImport.update({
  id: '/v8_/preview',
  path: '/v8/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const V8testKangxuanRoute = V8testKangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V8testRoute,
} as any)
const V8testRianRoute = V8testRianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V8testRoute,
} as any)
const V9KangxuanRoute = V9KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V9Route,
} as any)
const V9RianRoute = V9RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V9Route,
} as any)
const V9testKangxuanRoute = V9testKangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V9testRoute,
} as any)
const V9testRianRoute = V9testRianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V9testRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v10CtlPanel': typeof V10CtlPanelRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v9': typeof V9RouteWithChildren
  '/v9test': typeof V9testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v9/kangxuan': typeof V9KangxuanRoute
  '/v9/rian': typeof V9RianRoute
  '/v9test/kangxuan': typeof V9testKangxuanRoute
  '/v9test/rian': typeof V9testRianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v10CtlPanel': typeof V10CtlPanelRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v9': typeof V9RouteWithChildren
  '/v9test': typeof V9testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v9/kangxuan': typeof V9KangxuanRoute
  '/v9/rian': typeof V9RianRoute
  '/v9test/kangxuan': typeof V9testKangxuanRoute
  '/v9test/rian': typeof V9testRianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v10CtlPanel': typeof V10CtlPanelRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v9': typeof V9RouteWithChildren
  '/v9test': typeof V9testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8_/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v9/kangxuan': typeof V9KangxuanRoute
  '/v9/rian': typeof V9RianRoute
  '/v9test/kangxuan': typeof V9testKangxuanRoute
  '/v9test/rian': typeof V9testRianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v10CtlPanel'
    | '/v8'
    | '/v8test'
    | '/v9'
    | '/v9test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v9/kangxuan'
    | '/v9/rian'
    | '/v9test/kangxuan'
    | '/v9test/rian'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v10CtlPanel'
    | '/v8'
    | '/v8test'
    | '/v9'
    | '/v9test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v9/kangxuan'
    | '/v9/rian'
    | '/v9test/kangxuan'
    | '/v9test/rian'
  id:
    | '__root__'
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v10CtlPanel'
    | '/v8'
    | '/v8test'
    | '/v9'
    | '/v9test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8_/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v9/kangxuan'
    | '/v9/rian'
    | '/v9test/kangxuan'
    | '/v9test/rian'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KangxuanRoute: typeof KangxuanRoute
  RianRoute: typeof RianRoute
  V10CtlPanelRoute: typeof V10CtlPanelRoute
  V8Route: typeof V8RouteWithChildren
  V8testRoute: typeof V8testRouteWithChildren
  V9Route: typeof V9RouteWithChildren
  V9testRoute: typeof V9testRouteWithChildren
  V8PreviewRoute: typeof V8PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kangxuan': {
      id: '/kangxuan'
      path: '/kangxuan'
      fullPath: '/kangxuan'
      preLoaderRoute: typeof KangxuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rian': {
      id: '/rian'
      path: '/rian'
      fullPath: '/rian'
      preLoaderRoute: typeof RianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v10CtlPanel': {
      id: '/v10CtlPanel'
      path: '/v10CtlPanel'
      fullPath: '/v10CtlPanel'
      preLoaderRoute: typeof V10CtlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8': {
      id: '/v8'
      path: '/v8'
      fullPath: '/v8'
      preLoaderRoute: typeof V8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8test': {
      id: '/v8test'
      path: '/v8test'
      fullPath: '/v8test'
      preLoaderRoute: typeof V8testRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9': {
      id: '/v9'
      path: '/v9'
      fullPath: '/v9'
      preLoaderRoute: typeof V9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v9test': {
      id: '/v9test'
      path: '/v9test'
      fullPath: '/v9test'
      preLoaderRoute: typeof V9testRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8/kangxuan': {
      id: '/v8/kangxuan'
      path: '/kangxuan'
      fullPath: '/v8/kangxuan'
      preLoaderRoute: typeof V8KangxuanRouteImport
      parentRoute: typeof V8Route
    }
    '/v8/rian': {
      id: '/v8/rian'
      path: '/rian'
      fullPath: '/v8/rian'
      preLoaderRoute: typeof V8RianRouteImport
      parentRoute: typeof V8Route
    }
    '/v8_/preview': {
      id: '/v8_/preview'
      path: '/v8/preview'
      fullPath: '/v8/preview'
      preLoaderRoute: typeof V8PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8test/kangxuan': {
      id: '/v8test/kangxuan'
      path: '/kangxuan'
      fullPath: '/v8test/kangxuan'
      preLoaderRoute: typeof V8testKangxuanRouteImport
      parentRoute: typeof V8testRoute
    }
    '/v8test/rian': {
      id: '/v8test/rian'
      path: '/rian'
      fullPath: '/v8test/rian'
      preLoaderRoute: typeof V8testRianRouteImport
      parentRoute: typeof V8testRoute
    }
    '/v9/kangxuan': {
      id: '/v9/kangxuan'
      path: '/kangxuan'
      fullPath: '/v9/kangxuan'
      preLoaderRoute: typeof V9KangxuanRouteImport
      parentRoute: typeof V9Route
    }
    '/v9/rian': {
      id: '/v9/rian'
      path: '/rian'
      fullPath: '/v9/rian'
      preLoaderRoute: typeof V9RianRouteImport
      parentRoute: typeof V9Route
    }
    '/v9test/kangxuan': {
      id: '/v9test/kangxuan'
      path: '/kangxuan'
      fullPath: '/v9test/kangxuan'
      preLoaderRoute: typeof V9testKangxuanRouteImport
      parentRoute: typeof V9testRoute
    }
    '/v9test/rian': {
      id: '/v9test/rian'
      path: '/rian'
      fullPath: '/v9test/rian'
      preLoaderRoute: typeof V9testRianRouteImport
      parentRoute: typeof V9testRoute
    }
  }
}

interface V8RouteChildren {
  V8KangxuanRoute: typeof V8KangxuanRoute
  V8RianRoute: typeof V8RianRoute
}

const V8RouteChildren: V8RouteChildren = {
  V8KangxuanRoute: V8KangxuanRoute,
  V8RianRoute: V8RianRoute,
}

const V8RouteWithChildren = V8Route._addFileChildren(V8RouteChildren)

interface V8testRouteChildren {
  V8testKangxuanRoute: typeof V8testKangxuanRoute
  V8testRianRoute: typeof V8testRianRoute
}

const V8testRouteChildren: V8testRouteChildren = {
  V8testKangxuanRoute: V8testKangxuanRoute,
  V8testRianRoute: V8testRianRoute,
}

const V8testRouteWithChildren =
  V8testRoute._addFileChildren(V8testRouteChildren)

interface V9RouteChildren {
  V9KangxuanRoute: typeof V9KangxuanRoute
  V9RianRoute: typeof V9RianRoute
}

const V9RouteChildren: V9RouteChildren = {
  V9KangxuanRoute: V9KangxuanRoute,
  V9RianRoute: V9RianRoute,
}

const V9RouteWithChildren = V9Route._addFileChildren(V9RouteChildren)

interface V9testRouteChildren {
  V9testKangxuanRoute: typeof V9testKangxuanRoute
  V9testRianRoute: typeof V9testRianRoute
}

const V9testRouteChildren: V9testRouteChildren = {
  V9testKangxuanRoute: V9testKangxuanRoute,
  V9testRianRoute: V9testRianRoute,
}

const V9testRouteWithChildren =
  V9testRoute._addFileChildren(V9testRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KangxuanRoute: KangxuanRoute,
  RianRoute: RianRoute,
  V10CtlPanelRoute: V10CtlPanelRoute,
  V8Route: V8RouteWithChildren,
  V8testRoute: V8testRouteWithChildren,
  V9Route: V9RouteWithChildren,
  V9testRoute: V9testRouteWithChildren,
  V8PreviewRoute: V8PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
