/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KangxuanRouteImport } from './routes/kangxuan'
import { Route as RianRouteImport } from './routes/rian'
import { Route as V8RouteImport } from './routes/v8'
import { Route as V8testRouteImport } from './routes/v8test'
import { Route as V8KangxuanRouteImport } from './routes/v8.kangxuan'
import { Route as V8RianRouteImport } from './routes/v8.rian'
import { Route as V8PreviewRouteImport } from './routes/v8_.preview'
import { Route as V8testKangxuanRouteImport } from './routes/v8test.kangxuan'
import { Route as V8testRianRouteImport } from './routes/v8test.rian'
import { Route as V8testMotionLabRouteImport } from './routes/v8test_.motion-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KangxuanRoute = KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => rootRouteImport,
} as any)
const RianRoute = RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => rootRouteImport,
} as any)
const V8Route = V8RouteImport.update({
  id: '/v8',
  path: '/v8',
  getParentRoute: () => rootRouteImport,
} as any)
const V8testRoute = V8testRouteImport.update({
  id: '/v8test',
  path: '/v8test',
  getParentRoute: () => rootRouteImport,
} as any)
const V8KangxuanRoute = V8KangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V8Route,
} as any)
const V8RianRoute = V8RianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V8Route,
} as any)
const V8PreviewRoute = V8PreviewRouteImport.update({
  id: '/v8_/preview',
  path: '/v8/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const V8testKangxuanRoute = V8testKangxuanRouteImport.update({
  id: '/kangxuan',
  path: '/kangxuan',
  getParentRoute: () => V8testRoute,
} as any)
const V8testRianRoute = V8testRianRouteImport.update({
  id: '/rian',
  path: '/rian',
  getParentRoute: () => V8testRoute,
} as any)
const V8testMotionLabRoute = V8testMotionLabRouteImport.update({
  id: '/v8test_/motion-lab',
  path: '/v8test/motion-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v8test/motion-lab': typeof V8testMotionLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v8test/motion-lab': typeof V8testMotionLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kangxuan': typeof KangxuanRoute
  '/rian': typeof RianRoute
  '/v8': typeof V8RouteWithChildren
  '/v8test': typeof V8testRouteWithChildren
  '/v8/kangxuan': typeof V8KangxuanRoute
  '/v8/rian': typeof V8RianRoute
  '/v8_/preview': typeof V8PreviewRoute
  '/v8test/kangxuan': typeof V8testKangxuanRoute
  '/v8test/rian': typeof V8testRianRoute
  '/v8test_/motion-lab': typeof V8testMotionLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v8'
    | '/v8test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v8test/motion-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v8'
    | '/v8test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v8test/motion-lab'
  id:
    | '__root__'
    | '/'
    | '/kangxuan'
    | '/rian'
    | '/v8'
    | '/v8test'
    | '/v8/kangxuan'
    | '/v8/rian'
    | '/v8_/preview'
    | '/v8test/kangxuan'
    | '/v8test/rian'
    | '/v8test_/motion-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KangxuanRoute: typeof KangxuanRoute
  RianRoute: typeof RianRoute
  V8Route: typeof V8RouteWithChildren
  V8testRoute: typeof V8testRouteWithChildren
  V8PreviewRoute: typeof V8PreviewRoute
  V8testMotionLabRoute: typeof V8testMotionLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kangxuan': {
      id: '/kangxuan'
      path: '/kangxuan'
      fullPath: '/kangxuan'
      preLoaderRoute: typeof KangxuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rian': {
      id: '/rian'
      path: '/rian'
      fullPath: '/rian'
      preLoaderRoute: typeof RianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8': {
      id: '/v8'
      path: '/v8'
      fullPath: '/v8'
      preLoaderRoute: typeof V8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8test': {
      id: '/v8test'
      path: '/v8test'
      fullPath: '/v8test'
      preLoaderRoute: typeof V8testRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8/kangxuan': {
      id: '/v8/kangxuan'
      path: '/kangxuan'
      fullPath: '/v8/kangxuan'
      preLoaderRoute: typeof V8KangxuanRouteImport
      parentRoute: typeof V8Route
    }
    '/v8/rian': {
      id: '/v8/rian'
      path: '/rian'
      fullPath: '/v8/rian'
      preLoaderRoute: typeof V8RianRouteImport
      parentRoute: typeof V8Route
    }
    '/v8_/preview': {
      id: '/v8_/preview'
      path: '/v8/preview'
      fullPath: '/v8/preview'
      preLoaderRoute: typeof V8PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v8test/kangxuan': {
      id: '/v8test/kangxuan'
      path: '/kangxuan'
      fullPath: '/v8test/kangxuan'
      preLoaderRoute: typeof V8testKangxuanRouteImport
      parentRoute: typeof V8testRoute
    }
    '/v8test/rian': {
      id: '/v8test/rian'
      path: '/rian'
      fullPath: '/v8test/rian'
      preLoaderRoute: typeof V8testRianRouteImport
      parentRoute: typeof V8testRoute
    }
    '/v8test_/motion-lab': {
      id: '/v8test_/motion-lab'
      path: '/v8test/motion-lab'
      fullPath: '/v8test/motion-lab'
      preLoaderRoute: typeof V8testMotionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface V8RouteChildren {
  V8KangxuanRoute: typeof V8KangxuanRoute
  V8RianRoute: typeof V8RianRoute
}

const V8RouteChildren: V8RouteChildren = {
  V8KangxuanRoute: V8KangxuanRoute,
  V8RianRoute: V8RianRoute,
}

const V8RouteWithChildren = V8Route._addFileChildren(V8RouteChildren)

interface V8testRouteChildren {
  V8testKangxuanRoute: typeof V8testKangxuanRoute
  V8testRianRoute: typeof V8testRianRoute
}

const V8testRouteChildren: V8testRouteChildren = {
  V8testKangxuanRoute: V8testKangxuanRoute,
  V8testRianRoute: V8testRianRoute,
}

const V8testRouteWithChildren =
  V8testRoute._addFileChildren(V8testRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KangxuanRoute: KangxuanRoute,
  RianRoute: RianRoute,
  V8Route: V8RouteWithChildren,
  V8testRoute: V8testRouteWithChildren,
  V8PreviewRoute: V8PreviewRoute,
  V8testMotionLabRoute: V8testMotionLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
